[package]
name = "ray_tracing_challenge"
version = "0.1.0"
authors = ["Neeru Uppalapati <neeru@umich.edu"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.7.0"